version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network

  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - web
    networks:
      - mongo-network


volumes:
  mongo-data:

networks:
  mongo-network: