version: '3.8'

services:
  web:
    build: ./beckend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - mongo-network


  frontend:
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - web
    networks:
      - mongo-network


volumes:
  mongo-data:

networks:
  mongo-network: